build:
    environment:
        php:
            version: 7.1
checks:
    php:
        code_rating: true
        duplication: true
tools:
    external_code_coverage:
        timeout: 3600
    php_code_coverage:
        enabled: true