language: php
php:
  - '7.1'
cache:
  directories:
    - vendor
install:
  - composer --prefer-source install
script:
  - phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
  email:
    - alekseeey@gmail.com